spring:
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: secret
  data:
    neo4j:
      database: neo4j
logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG